---
- name: "Load a variable file based on the OS type, or a default if not found"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    -  "{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
    - default.yaml

- name: "Install system packages"
  package:
    name: '{{ system_packages }}'
    # use: '{{ ansible_pkg_mgr }}'
    state: present


- name: oracle java license accept
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: adding apt repo for oracle java
  # apt_repository: repo='ppa:webupd8team/java' state=present update_cache=yes #fatal: [vg-docker-01]: FAILED! => {"changed": false, "msg": "apt cache update failed"}
  apt_repository: repo=ppa:webupd8team/java state=present

- name: install java wget nginx apache2 and utils
  apt: name={{ item }} state=present update_cache=yes

  with_items:
    - oracle-java8-installer
    - nginx
    - apache2-utils
    - python-pip
    - git
    - python-passlib


#- include: certificates.yml
- include: nginx.yml
